# Generated by Django 2.2.2 on 2019-09-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('product_name', models.CharField(max_length=100, unique=True, verbose_name='产品名称')),
                ('product_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='产品描述')),
                ('product_user', models.CharField(max_length=32, verbose_name='产品负责人')),
                ('creater_time', models.IntegerField(default=1567487788, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品管理',
                'verbose_name_plural': '产品管理',
                'db_table': 'tp_product',
            },
        ),
    ]
