# Generated by Django 2.2.2 on 2019-09-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creater_time',
            field=models.IntegerField(default=1567488030, verbose_name='创建时间'),
        ),
    ]
