# Generated by Django 2.1.4 on 2019-08-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190826_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='产品描述'),
        ),
    ]
