# Generated by Django 2.2.2 on 2019-08-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190827_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creater_time',
            field=models.IntegerField(default=1567044847, verbose_name='创建时间'),
        ),
    ]
