# Generated by Django 2.2.2 on 2019-08-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190829_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creater_time',
            field=models.IntegerField(default=1567045668, max_length=10, verbose_name='创建时间'),
        ),
    ]
