# Generated by Django 2.2.2 on 2019-08-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190829_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creater_time',
            field=models.CharField(default=1567046104, max_length=10, verbose_name='创建时间'),
        ),
    ]
