# Generated by Django 2.2.2 on 2019-08-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190829_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creater_time',
            field=models.BigIntegerField(verbose_name='创建时间'),
        ),
    ]
