# Generated by Django 2.2.2 on 2019-08-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190829_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creater_time',
            field=models.IntegerField(default=1567131229, verbose_name='创建时间'),
        ),
    ]
