# Generated by Django 2.1.4 on 2019-08-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190830_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creater_time',
            field=models.IntegerField(default=1567227361, verbose_name='创建时间'),
        ),
    ]
